#!/bin/bash
# $Id$
#
# /etc/hotplug/usb/usbcam
#
# Sets up newly plugged in USB camera so that the user who owns
# the console according to pam_console can access it from user space
#
# Note that for this script to work, you'll need all of the following:
# a) a line in the file /etc/hotplug/usermap that corresponds to the 
#    camera you are using. You can get the correct lines for all cameras 
#    supported by gphoto2 by running "gphoto2 --print-usb-usermap".
# b) a setup using pam_console creates the respective lock files
#    containing the name of the respective user. You can check for that
#    by executing "echo `cat /var/{run,lock}/console.lock`" and 
#    verifying the appropriate user is mentioned somewhere there.
# c) a Linux kernel supporting hotplug and usbdevfs
# d) the hotplug package (http://linux-hotplug.sourceforge.net/)
#
# In the usermap file, the first field "usb module" should be named 
# "usbcam" like this script.
# 
# Adapted for use with BitPim by Joe Pham <djpham@bitpim.org>
#

export LD_LIBRARY_PATH="/usr/local/lib;/usr/lib;/lib"

logfile='/dev/null'
# logfile='/tmp/usbcell.log'

echo "${ACTION}" "${DEVICE}" "${INTERFACE}" >& $logfile

if [ "${ACTION}" = "add" ] && [ -f "${DEVICE}" ]
then
    # New code, using lock files instead of copying /dev/console permissions
    # This also works with non-gdm logins (e.g. on a virtual terminal)
    # Idea and code from Nalin Dahyabhai <nalin@redhat.com>
    if [ -f /var/run/console.lock ]
    then
        CONSOLEOWNER=`cat /var/run/console.lock`
    elif [ -f /var/lock/console.lock ]
    then
        CONSOLEOWNER=`cat /var/lock/console.lock`
    else
        CONSOLEOWNER=
    fi
    if [ -n "$CONSOLEOWNER" ]
    then
        chmod 0000 "${DEVICE}"
        chown "$CONSOLEOWNER" "${DEVICE}"
        chmod 0600 "${DEVICE}"
    fi
    if [ -x /usr/bin/bitpim ]
    then
        /usr/bin/bitpim -a "${DEVICE}" >> $logfile 2>&1
    fi
elif [ "${ACTION}" = "remove" ] && [ -x /usr/bin/bitpim ]
then
    /usr/bin/bitpim -r "${DEVICE}" >> $logfile 2>&1
fi
