
#ifdef _HELP_PREVIOUS_FILE						
TEXTLINK(_HELP_PREVIOUS_FILE,_HELP_PREVIOUS_TITLE,Previous)		
#endif									
#ifdef _HELP_PARENT_FILE						
TEXTLINK(_HELP_PARENT_FILE,_HELP_PARENT_TITLE,Up)			
#endif									
#ifdef _HELP_NEXT_FILE							
TEXTLINK(_HELP_NEXT_FILE,_HELP_NEXT_TITLE,Next)
#endif
