# Automatically generated file
# Generated by $Id$ on
# Wed Aug 20 23:35:37 2003
# DO NOT EDIT

ID_WELCOME="welcome.htm"
ID_VERSION_HISTORY="versionhistory.htm"
ID_TOUR="tour-master.htm"
ID_SETTINGS_DIALOG="ref-settings.htm"
