# Automatically generated file
# Generated by Id: genids.py,v 1.4 2003/09/01 21:04:18 rogerb Exp 
# DO NOT EDIT

'''IDs that map from constants to sections within the help

@Note: This is an autogenerated file.  See my source for details.
'''
ID_COMMSETTINGS_DIALOG="ref-commsettingsdialog.htm"
ID_DEVICE_NEEDS_ATTENTION="errors-deviceneedsattention.htm"
ID_EXCEPTION_DIALOG="errors-exception.htm"
ID_FAILED_TO_AUTODETECT_PORT="errors-failedtoautodetectport.htm"
ID_FAILED_TO_OPEN_DEVICE="errors-failedtoopendevice.htm"
ID_HEXVIEW_DIALOG="ref-hexviewdialog.htm"
ID_INVALID_FILE_MESSAGE="error-invalidimagefile.htm"
ID_MIME_EXEC_FAILED="errors-mimeexecfailed.htm"
ID_NO_MIME_OPEN="errors-nomimeopencommand.htm"
ID_SETTINGS_DIALOG="ref-settings.htm"
ID_TOUR="tour-master.htm"
ID_VERSION_HISTORY="versionhistory.htm"
ID_WELCOME="welcome.htm"
